RISK = {
    "Alabama": "Worst",
    "Arkansas": "Worst",
    "Florida": "Worst",
    "Oklahoma": "Worst",
    "Tennessee": "Worst",
    "Texas": "Worst",
    "Idaho": "High",
    "Indiana": "High",
    "Kentucky": "High",
    "Louisiana": "High",
    "Mississippi": "High",
    "Missouri": "High",
    "Montana": "High",
    "Ohio": "High",
    "South Carolina": "High",
    "South Dakota": "High",
    "Utah": "Worst",
    "Virginia": "High",
    "West Virginia": "High",
    "Alaska": "Moderate",
    "Georgia": "Moderate",
    "Iowa": "High",
    "Kansas": "Moderate",
    "Nebraska": "High",
    "New Hampshire": "Moderate",
    "North Carolina": "Moderate",
    "North Dakota": "High",
    "Wyoming": "High",
    "Arizona": "Low",
    "Delaware": "Low",
    "Maine": "Low",
    "Maryland": "Low",
    "Michigan": "Low",
    "Minnesota": "Low",
    "Nevada": "Low",
    "New Jersey": "Low",
    "New Mexico": "Low",
    "Pennsylvania": "Low",
    "Rhode Island": "Low",
    "Wisconsin": "Low",
    "California": "Safest",
    "Colorado": "Safest",
    "Connecticut": "Safest",
    "Hawaii": "Safest",
    "Illinois": "Safest",
    "Massachusetts": "Safest",
    "New York": "Safest",
    "Oregon": "Safest",
    "Vermont": "Safest",
    "Washington": "Safest",
    "DC": "Safest",
    "US": "Low"
}