RISK = {
    "Alabama": "Worst",
    "Arkansas": "Worst",
    "Florida": "DO NOT TRAVEL",
    "Oklahoma": "Worst",
    "Tennessee": "Worst",
    "Texas": "Worst",
    "Idaho": "Worst",
    "Indiana": "Worst",
    "Kentucky": "Worst",
    "Louisiana": "High",
    "Mississippi": "Worst",
    "Missouri": "Worst",
    "Montana": "Worst",
    "Ohio": "High",
    "South Carolina": "High",
    "South Dakota": "Worst",
    "Utah": "Worst",
    "Virginia": "High",
    "West Virginia": "High",
    "Alaska": "Moderate",
    "Georgia": "Worst",
    "Iowa": "Wprst",
    "Kansas": "Worst",
    "Nebraska": "Worst",
    "New Hampshire": "Moderate",
    "North Carolina": "High",
    "North Dakota": "Worst",
    "Wyoming": "High",
    "Arizona": "Low",
    "Delaware": "Low",
    "Maine": "Low",
    "Maryland": "Safest",
    "Michigan": "Low",
    "Minnesota": "Safest",
    "Nevada": "Low",
    "New Jersey": "Safest",
    "New Mexico": "Safest",
    "Pennsylvania": "Low",
    "Rhode Island": "Low",
    "Wisconsin": "Low",
    "California": "Safest",
    "Colorado": "Safest",
    "Connecticut": "Safest",
    "Hawaii": "Safest",
    "Illinois": "Safest",
    "Massachusetts": "Safest",
    "New York": "Safest",
    "Oregon": "Safest",
    "Vermont": "Safest",
    "Washington": "Safest",
    "DC": "Safest",
    "US": "Low"
}

COLOR = {
    "DO NOT TRAVEL": 0x741211,
    "Worst": 0x981904,
    "High": 0xcf4602,
    "Moderate": 0xf29778,
    "Low": 0xb8e3e9,
    "Safest": 0x12b3c5
}