SESSIONS = [{"session_id": 2014, "state_id": 1, "year_start": 2023, "year_end": 2023, "prefile": 0, "sine_die": 0,
             "prior": 0, "special": 0, "session_tag": "Regular Session", "session_title": "2023 Regular Session",
             "session_name": "Regular Session 2023", "dataset_hash": None, "session_hash": None,
             "name": "Regular Session 2023"}, {"session_id": 2015, "state_id": 2, "year_start": 2023, "year_end": 2024,
                                               "prefile": 0, "sine_die": 0, "prior": 0, "special": 0,
                                               "session_tag": "Regular Session",
                                               "session_title": "2023-2024 Regular Session",
                                               "session_name": "33rd Legislature", "dataset_hash": None,
                                               "session_hash": None, "name": "33rd Legislature"}, {"session_id": 2010,
                                                                                                   "state_id": 3,
                                                                                                   "year_start": 2023,
                                                                                                   "year_end": 2023,
                                                                                                   "prefile": 1,
                                                                                                   "sine_die": 0,
                                                                                                   "prior": 0,
                                                                                                   "special": 0,
                                                                                                   "session_tag": "Regular Session",
                                                                                                   "session_title": "2023 Regular Session",
                                                                                                   "session_name": "Fifty-sixth Legislature - First Regular Session (2023)",
                                                                                                   "dataset_hash": "643a88dc51a6ff08b3e3bec6c32c32df",
                                                                                                   "session_hash": "643a88dc51a6ff08b3e3bec6c32c32df",
                                                                                                   "name": "Fifty-sixth Legislature - First Regular Session (2023)"},
            {
                "session_id": 2004, "state_id": 4, "year_start": 2023, "year_end": 2023, "prefile": 1, "sine_die": 0,
                "prior": 0,
                "special": 0, "session_tag": "Regular Session", "session_title": "2023 Regular Session",
                "session_name": "94th General Assembly (2023 Regular)",
                "dataset_hash": "45e9c9b6b8c243b4b1ebeed9cd6ce9a0",
                "session_hash": "45e9c9b6b8c243b4b1ebeed9cd6ce9a0", "name": "94th General Assembly (2023 Regular)"}, {
                "session_id": 2016, "state_id": 5, "year_start": 2023, "year_end": 2024, "prefile": 0, "sine_die": 0,
                "prior": 0,
                "special": 0, "session_tag": "Regular Session", "session_title": "2023-2024 Regular Session",
                "session_name": "2023-2024 Session", "dataset_hash": "5289739ba4a4963e00c301bcac116f3b",
                "session_hash": "5289739ba4a4963e00c301bcac116f3b", "name": "2023-2024 Regular Session"},
            {"session_id": 2017,
             "state_id": 6,
             "year_start": 2023,
             "year_end": 2023,
             "prefile": 0,
             "sine_die": 0,
             "prior": 0, "special": 0,
             "session_tag": "Regular Session",
             "session_title": "2023 Regular Session",
             "session_name": "2023 Regular Session",
             "dataset_hash": None,
             "session_hash": None,
             "name": "2023 Regular Session"}, {
                "session_id": 2018, "state_id": 7, "year_start": 2023, "year_end": 2023, "prefile": 0, "sine_die": 0,
                "prior": 0,
                "special": 0, "session_tag": "Regular Session", "session_title": "2023 Regular Session",
                "session_name": "2023 General Assembly", "dataset_hash": None, "session_hash": None,
                "name": "2023 General Assembly"},
            {"session_id": 2005, "state_id": 8, "year_start": 2023, "year_end": 2024,
             "prefile": 1, "sine_die": 0, "prior": 0, "special": 0,
             "session_tag": "Regular Session", "session_title": "2023-2024 Regular Session",
             "session_name": "152nd General Assembly",
             "dataset_hash": "d28c3d76e2fc392c78fccb65a68dd91f",
             "session_hash": "d28c3d76e2fc392c78fccb65a68dd91f",
             "name": "152nd General Assembly"}, {"session_id": 1987, "state_id": 9,
                                                 "year_start": 2023, "year_end": 2023,
                                                 "prefile": 1, "sine_die": 0, "prior": 0,
                                                 "special": 0,
                                                 "session_tag": "Regular Session",
                                                 "session_title": "2023 Regular Session",
                                                 "session_name": "2023 Regular Session",
                                                 "dataset_hash": "f92ab4748b1a78da5b2028d2489d4490",
                                                 "session_hash": "f92ab4748b1a78da5b2028d2489d4490",
                                                 "name": "2023 Regular Session"}, {
                "session_id": 2008, "state_id": 10, "year_start": 2023, "year_end": 2024, "prefile": 1, "sine_die": 0,
                "prior": 0,
                "special": 0, "session_tag": "Regular Session", "session_title": "2023-2024 Regular Session",
                "session_name": "2023-2024 Regular Session", "dataset_hash": "d514bc0ec1dbc9c3b9c009415de578ec",
                "session_hash": "d514bc0ec1dbc9c3b9c009415de578ec", "name": "2023-2024 Regular Session"},
            {"session_id": 2019,
             "state_id": 11,
             "year_start": 2023,
             "year_end": 2023,
             "prefile": 0,
             "sine_die": 0,
             "prior": 0, "special": 0,
             "session_tag": "Regular Session",
             "session_title": "2023 Regular Session",
             "session_name": "2023 Regular Session",
             "dataset_hash": None,
             "session_hash": None,
             "name": "2023 Regular Session"}, {
                "session_id": 2011, "state_id": 12, "year_start": 2023, "year_end": 2023, "prefile": 0, "sine_die": 0,
                "prior": 0,
                "special": 0, "session_tag": "Regular Session", "session_title": "2023 Regular Session",
                "session_name": "2023 Regular Session", "dataset_hash": None, "session_hash": None,
                "name": "2023 Regular Session"},
            {"session_id": 2020, "state_id": 13, "year_start": 2023, "year_end": 2024,
             "prefile": 1, "sine_die": 0, "prior": 0, "special": 0,
             "session_tag": "Regular Session", "session_title": "2023-2024 Regular Session",
             "session_name": "103rd General Assembly",
             "dataset_hash": "7c6a710b73b7da4c8f7c5e99c3b57076",
             "session_hash": "7c6a710b73b7da4c8f7c5e99c3b57076",
             "name": "103rd General Assembly"}, {"session_id": 2021, "state_id": 14,
                                                 "year_start": 2023, "year_end": 2023,
                                                 "prefile": 0, "sine_die": 0, "prior": 0,
                                                 "special": 0,
                                                 "session_tag": "Regular Session",
                                                 "session_title": "2023 Regular Session",
                                                 "session_name": "2023 Regular Session",
                                                 "dataset_hash": None, "session_hash": None,
                                                 "name": "2023 Regular Session"}, {
                "session_id": 2022, "state_id": 15, "year_start": 2023, "year_end": 2024, "prefile": 0, "sine_die": 0,
                "prior": 0,
                "special": 0, "session_tag": "Regular Session", "session_title": "2023-2024 Regular Session",
                "session_name": "90th General Assembly", "dataset_hash": None, "session_hash": None,
                "name": "90th General Assembly"},
            {"session_id": 2023, "state_id": 16, "year_start": 2023, "year_end": 2024,
             "prefile": 1, "sine_die": 0, "prior": 0, "special": 0,
             "session_tag": "Regular Session", "session_title": "2023-2024 Regular Session",
             "session_name": "2023-2024 Regular Session", "dataset_hash": None,
             "session_hash": None, "name": "2023-2024 Regular Session"}, {"session_id": 2024,
                                                                          "state_id": 17,
                                                                          "year_start": 2023,
                                                                          "year_end": 2023,
                                                                          "prefile": 0,
                                                                          "sine_die": 0,
                                                                          "prior": 0,
                                                                          "special": 0,
                                                                          "session_tag": "Regular Session",
                                                                          "session_title": "2023 Regular Session",
                                                                          "session_name": "2023 Regular Session",
                                                                          "dataset_hash": None,
                                                                          "session_hash": None,
                                                                          "name": "2023 Regular Session"}, {
                "session_id": 2025, "state_id": 18, "year_start": 2023, "year_end": 2023, "prefile": 0, "sine_die": 0,
                "prior": 0,
                "special": 0, "session_tag": "Regular Session", "session_title": "2023 Regular Session",
                "session_name": "2023 Regular Session", "dataset_hash": None, "session_hash": None,
                "name": "2023 Regular Session"},
            {"session_id": 2013, "state_id": 19, "year_start": 2023, "year_end": 2024,
             "prefile": 0, "sine_die": 0, "prior": 0, "special": 0,
             "session_tag": "Regular Session", "session_title": "2023-2024 Regular Session",
             "session_name": "131st Legislature",
             "dataset_hash": "173981893b1abb2bb971d5f1c9592834",
             "session_hash": "173981893b1abb2bb971d5f1c9592834",
             "name": "131st Legislature"}, {"session_id": 2006, "state_id": 20,
                                            "year_start": 2023, "year_end": 2023, "prefile": 0,
                                            "sine_die": 0, "prior": 0, "special": 0,
                                            "session_tag": "Regular Session",
                                            "session_title": "2023 Regular Session",
                                            "session_name": "2023 Regular Session",
                                            "dataset_hash": None, "session_hash": None,
                                            "name": "2023 Regular Session"}, {
                "session_id": 2026, "state_id": 21, "year_start": 2023, "year_end": 2024, "prefile": 0, "sine_die": 0,
                "prior": 0,
                "special": 0, "session_tag": "Regular Session", "session_title": "2023-2024 Regular Session",
                "session_name": "193rd General Court", "dataset_hash": None, "session_hash": None,
                "name": "193rd General Court"}, {
                "session_id": 2027, "state_id": 22, "year_start": 2023, "year_end": 2024, "prefile": 0, "sine_die": 0,
                "prior": 0,
                "special": 0, "session_tag": "Regular Session", "session_title": "2023-2024 Regular Session",
                "session_name": "102nd Legislature", "dataset_hash": None, "session_hash": None,
                "name": "102nd Legislature"}, {
                "session_id": 1986, "state_id": 23, "year_start": 2023, "year_end": 2024, "prefile": 0, "sine_die": 0,
                "prior": 0,
                "special": 0, "session_tag": "Regular Session", "session_title": "2023-2024 Regular Session",
                "session_name": "93rd Legislature 2023-2024", "dataset_hash": None, "session_hash": None,
                "name": "93rd Legislature 2023-2024"},
            {"session_id": 1998, "state_id": 24, "year_start": 2023, "year_end": 2023,
             "prefile": 0, "sine_die": 0, "prior": 0, "special": 0,
             "session_tag": "Regular Session", "session_title": "2023 Regular Session",
             "session_name": "2023 Regular Session", "dataset_hash": None,
             "session_hash": None, "name": "2023 Regular Session"}, {"session_id": 2012,
                                                                     "state_id": 25,
                                                                     "year_start": 2023,
                                                                     "year_end": 2023,
                                                                     "prefile": 0,
                                                                     "sine_die": 0,
                                                                     "prior": 0,
                                                                     "special": 0,
                                                                     "session_tag": "Regular Session",
                                                                     "session_title": "2023 Regular Session",
                                                                     "session_name": "2023 Regular Session",
                                                                     "dataset_hash": "aa564818034ce8e735bc683a5edb6771",
                                                                     "session_hash": "aa564818034ce8e735bc683a5edb6771",
                                                                     "name": "2023 Regular Session"}, {
                "session_id": 1991, "state_id": 26, "year_start": 2023, "year_end": 2023, "prefile": 0, "sine_die": 0,
                "prior": 0,
                "special": 0, "session_tag": "Regular Session", "session_title": "2023 Regular Session",
                "session_name": "2023 Regular Session", "dataset_hash": "bdbd297bd4453399bfb03cc376c7daf1",
                "session_hash": "bdbd297bd4453399bfb03cc376c7daf1", "name": "2023 Regular Session"},
            {"session_id": 2028,
             "state_id": 27,
             "year_start": 2023,
             "year_end": 2024,
             "prefile": 0, "sine_die": 0,
             "prior": 0, "special": 0,
             "session_tag": "Regular Session",
             "session_title": "2023-2024 Regular Session",
             "session_name": "108th Legislature",
             "dataset_hash": None,
             "session_hash": None,
             "name": "108th Legislature"}, {
                "session_id": 1981, "state_id": 28, "year_start": 2023, "year_end": 2023, "prefile": 1, "sine_die": 0,
                "prior": 0,
                "special": 0, "session_tag": "Regular Session", "session_title": "2023 Regular Session",
                "session_name": "82nd Legislature (2023)", "dataset_hash": "74f2de7fddb9badebfe56390926737ed",
                "session_hash": "74f2de7fddb9badebfe56390926737ed", "name": "82nd Legislature (2023)"},
            {"session_id": 2029,
             "state_id": 29,
             "year_start": 2023,
             "year_end": 2023,
             "prefile": 0,
             "sine_die": 0, "prior": 0,
             "special": 0,
             "session_tag": "Regular Session",
             "session_title": "2023 Regular Session",
             "session_name": "2023 Regular Session",
             "dataset_hash": "dbc4e2420fd0a755f428136ff5ba865c",
             "session_hash": "dbc4e2420fd0a755f428136ff5ba865c",
             "name": "2023 Regular Session"}, {
                "session_id": 1960, "state_id": 30, "year_start": 2022, "year_end": 2023, "prefile": 0, "sine_die": 0,
                "prior": 0,
                "special": 0, "session_tag": "Regular Session", "session_title": "2022-2023 Regular Session",
                "session_name": "2022-2023 Regular Session", "dataset_hash": "76f3a478018171be4aa77e8bae98d1ab",
                "session_hash": "76f3a478018171be4aa77e8bae98d1ab", "name": "2022-2023 Regular Session"},
            {"session_id": 2030,
             "state_id": 31,
             "year_start": 2023,
             "year_end": 2023,
             "prefile": 1,
             "sine_die": 0,
             "prior": 0, "special": 0,
             "session_tag": "Regular Session",
             "session_title": "2023 Regular Session",
             "session_name": "2023 Regular Session",
             "dataset_hash": None,
             "session_hash": None,
             "name": "2023 Regular Session"}, {
                "session_id": 2031, "state_id": 32, "year_start": 2023, "year_end": 2024, "prefile": 0, "sine_die": 0,
                "prior": 0,
                "special": 0, "session_tag": "Regular Session", "session_title": "2023-2024 Regular Session",
                "session_name": "2023-2024 General Assembly", "dataset_hash": "3817fc68a0dde144606f8ed5c656a628",
                "session_hash": "3817fc68a0dde144606f8ed5c656a628", "name": "2023-2024 General Assembly"},
            {"session_id": 2032,
             "state_id": 33,
             "year_start": 2023,
             "year_end": 2024,
             "prefile": 0,
             "sine_die": 0,
             "prior": 0,
             "special": 0,
             "session_tag": "Regular Session",
             "session_title": "2023-2024 Regular Session",
             "session_name": "2023-2024 Session",
             "dataset_hash": None,
             "session_hash": None,
             "name": "2023-2024 Session"}, {
                "session_id": 1848, "state_id": 34, "year_start": 2023, "year_end": 2024, "prefile": 0, "sine_die": 0,
                "prior": 0,
                "special": 0, "session_tag": "Regular Session", "session_title": "2023-2024 Regular Session",
                "session_name": "68th Legislative Assembly", "dataset_hash": "bc32c9f21e3825969c80e7a3e9647b9f",
                "session_hash": "bc32c9f21e3825969c80e7a3e9647b9f", "name": "68th Legislative Assembly"},
            {"session_id": 2033,
             "state_id": 35,
             "year_start": 2023,
             "year_end": 2024,
             "prefile": 0,
             "sine_die": 0,
             "prior": 0, "special": 0,
             "session_tag": "Regular Session",
             "session_title": "2023-2024 Regular Session",
             "session_name": "135th General Assembly (2023-2024)",
             "dataset_hash": None,
             "session_hash": None,
             "name": "135th General Assembly"}, {
                "session_id": 1983, "state_id": 36, "year_start": 2023, "year_end": 2023, "prefile": 1, "sine_die": 0,
                "prior": 0,
                "special": 0, "session_tag": "Regular Session", "session_title": "2023 Regular Session",
                "session_name": "2023 Regular Session", "dataset_hash": "deb4b4dd0226d54fe7d2f4fba110125a",
                "session_hash": "deb4b4dd0226d54fe7d2f4fba110125a", "name": "2023 Regular Session"},
            {"session_id": 2034,
             "state_id": 37,
             "year_start": 2023,
             "year_end": 2023,
             "prefile": 0, "sine_die": 0,
             "prior": 0, "special": 0,
             "session_tag": "Regular Session",
             "session_title": "2023 Regular Session",
             "session_name": "2023 Legislative Measures",
             "dataset_hash": None,
             "session_hash": None,
             "name": "2023 Legislative Measures"}, {
                "session_id": 2035, "state_id": 38, "year_start": 2023, "year_end": 2024, "prefile": 0, "sine_die": 0,
                "prior": 0,
                "special": 0, "session_tag": "Regular Session", "session_title": "2023-2024 Regular Session",
                "session_name": "2023-2024 Regular Session", "dataset_hash": None, "session_hash": None,
                "name": "2023-2024 Regular Session"},
            {"session_id": 2036, "state_id": 39, "year_start": 2023, "year_end": 2023,
             "prefile": 0, "sine_die": 0, "prior": 0, "special": 0,
             "session_tag": "Regular Session", "session_title": "2023 Regular Session",
             "session_name": "2023 Regular Session", "dataset_hash": None,
             "session_hash": None, "name": "2023 Regular Session"}, {"session_id": 2007,
                                                                     "state_id": 40,
                                                                     "year_start": 2023,
                                                                     "year_end": 2024,
                                                                     "prefile": 1,
                                                                     "sine_die": 0,
                                                                     "prior": 0,
                                                                     "special": 0,
                                                                     "session_tag": "Regular Session",
                                                                     "session_title": "2023-2024 Regular Session",
                                                                     "session_name": "125th General Assembly",
                                                                     "dataset_hash": "d23f411e86592956edf7965f3e07ef2b",
                                                                     "session_hash": "d23f411e86592956edf7965f3e07ef2b",
                                                                     "name": "125th General Assembly"}, {
                "session_id": 2001, "state_id": 41, "year_start": 2023, "year_end": 2023, "prefile": 1, "sine_die": 0,
                "prior": 0,
                "special": 0, "session_tag": "Regular Session", "session_title": "2023 Regular Session",
                "session_name": "2023 Regular Session", "dataset_hash": "09dea3e68c48f3b460b3b5256b9af0a8",
                "session_hash": "09dea3e68c48f3b460b3b5256b9af0a8", "name": "2023 Regular Session"},
            {"session_id": 2002,
             "state_id": 42,
             "year_start": 2023,
             "year_end": 2024,
             "prefile": 1, "sine_die": 0,
             "prior": 0, "special": 0,
             "session_tag": "Regular Session",
             "session_title": "2023-2024 Regular Session",
             "session_name": "113th General Assembly",
             "dataset_hash": "e55e656d11a58efa31576219f0faf3e9",
             "session_hash": "e55e656d11a58efa31576219f0faf3e9",
             "name": "113th General Assembly"}, {
                "session_id": 2003, "state_id": 43, "year_start": 2023, "year_end": 2024, "prefile": 1, "sine_die": 0,
                "prior": 0,
                "special": 0, "session_tag": "Regular Session", "session_title": "2023 Regular Session",
                "session_name": "88th Legislature Regular Session", "dataset_hash": "e796aa0607204ffcadbe4b2259640731",
                "session_hash": "e796aa0607204ffcadbe4b2259640731", "name": "88th Legislature Regular Session"}, {
                "session_id": 1978, "state_id": 44, "year_start": 2023, "year_end": 2023, "prefile": 1, "sine_die": 0,
                "prior": 0,
                "special": 0, "session_tag": "Regular Session", "session_title": "2023 Regular Session",
                "session_name": "2023 General Session", "dataset_hash": "9e5b5444777a76b226ed4e45b8c2ad7f",
                "session_hash": "9e5b5444777a76b226ed4e45b8c2ad7f", "name": "2023 General Session"},
            {"session_id": 2009,
             "state_id": 45,
             "year_start": 2023,
             "year_end": 2024,
             "prefile": 0, "sine_die": 0,
             "prior": 0, "special": 0,
             "session_tag": "Regular Session",
             "session_title": "2023-2024 Regular Session",
             "session_name": "2023-2024 Session",
             "dataset_hash": None,
             "session_hash": None,
             "name": "2023-2024 Session"}, {
                "session_id": 1988, "state_id": 46, "year_start": 2023, "year_end": 2023, "prefile": 1, "sine_die": 0,
                "prior": 0,
                "special": 0, "session_tag": "Regular Session", "session_title": "2023 Regular Session",
                "session_name": "2023 Regular Session", "dataset_hash": "8d68bf0108e86e5d1fea940552bb3333",
                "session_hash": "8d68bf0108e86e5d1fea940552bb3333", "name": "2023 Regular Session"},
            {"session_id": 2037,
             "state_id": 47,
             "year_start": 2023,
             "year_end": 2024,
             "prefile": 1, "sine_die": 0,
             "prior": 0, "special": 0,
             "session_tag": "Regular Session",
             "session_title": "2023-2024 Regular Session",
             "session_name": "2023-2024 Regular Session",
             "dataset_hash": "f060b7e006003da7b578838d62f0cee7",
             "session_hash": "f060b7e006003da7b578838d62f0cee7",
             "name": "2023-2024 Regular Session"}, {
                "session_id": 2038, "state_id": 48, "year_start": 2023, "year_end": 2023, "prefile": 0, "sine_die": 0,
                "prior": 0,
                "special": 0, "session_tag": "Regular Session", "session_title": "2023 Regular Session",
                "session_name": "2023 Regular Session", "dataset_hash": None, "session_hash": None,
                "name": "2023 Regular Session"},
            {"session_id": 2039, "state_id": 49, "year_start": 2023, "year_end": 2024,
             "prefile": 0, "sine_die": 0, "prior": 0, "special": 0,
             "session_tag": "Regular Session", "session_title": "2023-2024 Regular Session",
             "session_name": "2023-2024 Regular Session", "dataset_hash": None,
             "session_hash": None, "name": "2023-2024 Regular Session"}, {"session_id": 1999,
                                                                          "state_id": 50,
                                                                          "year_start": 2023,
                                                                          "year_end": 2023,
                                                                          "prefile": 1,
                                                                          "sine_die": 0,
                                                                          "prior": 0,
                                                                          "special": 0,
                                                                          "session_tag": "Regular Session",
                                                                          "session_title": "2023 Regular Session",
                                                                          "session_name": "2023 General Session",
                                                                          "dataset_hash": "29da23f267a5f3a146d417774a4de68e",
                                                                          "session_hash": "29da23f267a5f3a146d417774a4de68e",
                                                                          "name": "2023 General Session"}, {
                "session_id": 2040, "state_id": 51, "year_start": 2023, "year_end": 2024, "prefile": 0, "sine_die": 0,
                "prior": 0,
                "special": 0, "session_tag": "Regular Session", "session_title": "2023-2024 Regular Session",
                "session_name": "25th Council", "dataset_hash": None, "session_hash": None, "name": "25th Council"}, {
                "session_id": 2041, "state_id": 52, "year_start": 2023, "year_end": 2024, "prefile": 0, "sine_die": 0,
                "prior": 0,
                "special": 0, "session_tag": "Regular Session", "session_title": "2023-2024 Regular Session",
                "session_name": "118th Congress", "dataset_hash": None, "session_hash": None, "name": "118th Congress"}]